name: test
on:
  workflow_dispatch:
   inputs:
      my_variable:
      type: string
      description: "test variable"
jobs:
  test:
    name: test
    steps:
     - name: test
       run: echo ${{ inputs.my_variable }}

