name: test
on:
  workflow_dispatch:
   inputs:
      project_name:
        type: string
        description: "name of the project"
      environment:
        type: string
        description: "environment"
      
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
     - name: Failure
       run: |
        if [ "${{ inputs.environment }}" == "nonproduction" ]; then
          URL="https://youtube.com"
        elif [ "${{ inputs.environment }}" == "preproduction" ]; then
          URL="https://google.com/maps"
        elif [ "${{ inputs.environment }}" == "production" ]; then
          URL="https://pax8.com"
        else
          echo "unknown environment"
          exit 1
        fi
        echo "Failed deploy see ArgoCD at $URL"


