name: test
on:
  workflow_dispatch:
   inputs:
      project_name:
        type: string
        description: "name of the project"
      environment:
        type: string
        description: "environment"
      
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
     - name: test
       run: echo ${{ inputs.project_name}}.${{ inputs.environment }}
     - name: Failure
       run: |
        if [ "${{ inputs.environment }}" == "nonproduction" ]; then
          URL="https://google.com/${{ inputs.project_name }}"
        elif [ "${{ inputs.environment }}" == "preproduction" ]; then
          URL="https://youtube.com"
        elif [ "${{ inputs.environment }}" == "production" ]; then
          URL="https://google.com"
        else
          URL="https://default.com"
        fi
        echo "Failed deploy see ArgoCD at $URL"
        exit 1


    #  - name: Failure
    #    run: |
    #     if [ "${{ inputs.environment }}" == "nonproduction" ]; then
    #       URL="https://google.com/${{ inputs.project_name }}"
    #     elif [ "${{ inputs.environment }}" == "preproduction" ]; then
    #       URL="https://youtube.com"
    #     else [ "${{ inputs.environment }}" == "production" ]; then
    #       URL="https://google.com"
    #     fi
    #     echo "Failed deploy see ArgoCD at $URL"
    #     exit 1

